# Generated by Django 5.0.4 on 2024-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('birth_date', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=50)),
                ('mother_lang', models.CharField(max_length=50)),
            ],
        ),
    ]
