# Generated by Django 5.0.4 on 2024-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/resumes/'),
        ),
    ]
